apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: arxiv-browse
  namespace: '874717964009'
  selfLink: /apis/serving.knative.dev/v1/namespaces/874717964009/services/arxiv-browse
  uid: 1916080f-934d-4f6d-81a0-0043b332b495
  resourceVersion: AAY/9A9socU
  generation: 543
  creationTimestamp: '2023-02-16T21:28:07.292661Z'
  labels:
    commit-sha: d4548e3a3952eae36f646a45554d973bd95482e3
    gcb-build-id: c5ad8bd7-b853-4ace-899d-38317821fc77
    gcb-trigger-id: d0018658-8a13-40f5-b20f-78582fb4135e
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
    cloud.googleapis.com/location: us-central1
  annotations:
    serving.knative.dev/creator: bcaruso@arxiv.org
    serving.knative.dev/lastModifier: 874717964009@cloudbuild.gserviceaccount.com
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 540.0.0
    run.googleapis.com/operation-id: 67658ab8-0133-4499-b816-20dff80bde47
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://arxiv-browse-874717964009.us-central1.run.app","https://arxiv-browse-6lhtms3oua-uc.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: vmunpiflhz
        commit-sha: d4548e3a3952eae36f646a45554d973bd95482e3
        gcb-build-id: c5ad8bd7-b853-4ace-899d-38317821fc77
        gcb-trigger-id: d0018658-8a13-40f5-b20f-78582fb4135e
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 540.0.0
        run.googleapis.com/cloudsql-instances: arxiv-development:us-east4:arxiv-db-dev,arxiv-development:us-central1:latexml-db
        run.googleapis.com/vpc-access-connector: projects/arxiv-development/locations/us-central1/connectors/clourrunconnector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 81
      timeoutSeconds: 300
      serviceAccountName: arxiv-browse-cloud-run@arxiv-development.iam.gserviceaccount.com
      containers:
      - name: arxiv-browse-1
        image: gcr.io/arxiv-development/arxiv-browse:d4548e3a3952eae36f646a45554d973bd95482e3
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: BASE_SERVER
          value: browse.dev.arxiv.org
        - name: DOCUMENT_ABSTRACT_SERVICE
          value: browse.services.documents.db_docs
        - name: DOCUMENT_LISTING_SERVICE
          value: browse.services.listing.db_listing
        - name: DOCUMENT_LISTING_PATH
          value: gs://arxiv-production-data/ftp
        - name: DISSEMINATION_STORAGE_PREFIX
          value: gs://arxiv-production-data
        - name: DOCUMENT_LATEST_VERSIONS_PATH
          value: gs://arxiv-production-data/ftp
        - name: DOCUMENT_ORIGNAL_VERSIONS_PATH
          value: gs://arxiv-production-data/orig
        - name: DOCUMENT_CACHE_PATH
          value: gs://arxiv-production-data/ps_cache
        - name: LATEXML_BASE_URL
          value: https://browse.dev.arxiv.org
        - name: HELP_SERVER
          value: info.dev.arxiv.org
        - name: CLASSIC_HTML_BUCKET
          value: arxiv-dev-html-papers
        - name: LATEXML_ENABLED
          value: '1'
        - name: GENPDF_API_URL
          value: '0'
        - name: GENPDF_API_TIMEOUT
          value: '590'
        - name: GENPDF_API_STORAGE_PREFIX
          value: gs://arxiv-sync-test-01
        - name: GENPDF_SERVICE_URL
          value: '0'
        - name: CLASSIC_DB_TRANSACTION_ISOLATION_LEVEL
          value: READ UNCOMMITTED
        - name: LATEXML_DB_TRANSACTION_ISOLATION_LEVEL
          value: READ UNCOMMITTED
        - name: SOURCE_STORAGE_PREFIX
          value: gs://arxiv-production-data
        - name: CLASSIC_DB_URI
          valueFrom:
            secretKeyRef:
              key: latest
              name: browse-sqlalchemy-db-uri
        - name: LATEXML_DB_URI
          valueFrom:
            secretKeyRef:
              key: latest
              name: latexml_db_uri_psycog2
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 60
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 543
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2025-09-29T17:35:23.611589Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2025-09-29T17:35:22.323478Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2025-09-29T17:35:23.570476Z'
  latestReadyRevisionName: arxiv-browse-00538-67r
  latestCreatedRevisionName: arxiv-browse-00538-67r
  traffic:
  - revisionName: arxiv-browse-00538-67r
    percent: 100
    latestRevision: true
  url: https://arxiv-browse-6lhtms3oua-uc.a.run.app
  address:
    url: https://arxiv-browse-6lhtms3oua-uc.a.run.app
