Date: Fri, 17 Mar 23 00:51:30 GMT
Subject: q-fin.CP daily Subj-class mailing

------------------------------------------------------------------------------
------------------------------------------------------------------------------
Send any comments regarding submissions directly to submitter.
------------------------------------------------------------------------------
Archives at http://arxiv.org/
To unsubscribe, e-mail To: q-fin@arXiv.org, Subject: cancel
------------------------------------------------------------------------------
 Submissions to:
Computational Finance
 received from  Wed 15 Mar 23 18:00:00 GMT  to  Thu 16 Mar 23 18:00:00 GMT
------------------------------------------------------------------------------
------------------------------------------------------------------------------
\\
arXiv:2303.08968
Date: Wed, 15 Mar 2023 22:37:33 GMT   (1742kb,D)

Title: A parsimonious neural network approach to solve portfolio optimization
  problems without using dynamic programming
Authors: Pieter M. van Staden and Peter A. Forsyth and Yuying Li
Categories: q-fin.CP
\\
  We present a parsimonious neural network approach, which does not rely on
dynamic programming techniques, to solve dynamic portfolio optimization
problems subject to multiple investment constraints. The number of parameters
of the (potentially deep) neural network remains independent of the number of
portfolio rebalancing events, and in contrast to, for example, reinforcement
learning, the approach avoids the computation of high-dimensional conditional
expectations. As a result, the approach remains practical even when considering
large numbers of underlying assets, long investment time horizons or very
frequent rebalancing events. We prove convergence of the numerical solution to
the theoretical optimal solution of a large class of problems under fairly
general conditions, and present ground truth analyses for a number of popular
formulations, including mean-variance and mean-conditional value-at-risk
problems. We also show that it is feasible to solve Sortino ratio-inspired
objectives (penalizing only the variance of wealth outcomes below the mean) in
dynamic trading settings with the proposed approach. Using numerical
experiments, we demonstrate that if the investment objective functional is
separable in the sense of dynamic programming, the correct time-consistent
optimal investment strategy is recovered, otherwise we obtain the correct
pre-commitment (time-inconsistent) investment strategy. The proposed approach
remains agnostic as to the underlying data generating assumptions, and results
are illustrated using (i) parametric models for underlying asset returns, (ii)
stationary block bootstrap resampling of empirical returns, and (iii)
generative adversarial network (GAN)-generated synthetic asset returns.
\\ ( https://arxiv.org/abs/2303.08968 ,  1742kb)
%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-
------------------------------------------------------------------------------
\\
arXiv:2303.09406 (*cross-listing*)
Date: Tue, 7 Mar 2023 17:24:04 GMT   (12840kb,D)

Title: Stock Price Prediction Using Temporal Graph Model with Value Chain Data
Authors: Chang Liu and Sandra Paterlini
Categories: q-fin.ST cs.LG q-fin.CP
\\
  Stock price prediction is a crucial element in financial trading as it allows
traders to make informed decisions about buying, selling, and holding stocks.
Accurate predictions of future stock prices can help traders optimize their
trading strategies and maximize their profits. In this paper, we introduce a
neural network-based stock return prediction method, the Long Short-Term Memory
Graph Convolutional Neural Network (LSTM-GCN) model, which combines the Graph
Convolutional Network (GCN) and Long Short-Term Memory (LSTM) Cells.
Specifically, the GCN is used to capture complex topological structures and
spatial dependence from value chain data, while the LSTM captures temporal
dependence and dynamic changes in stock returns data. We evaluated the LSTM-GCN
model on two datasets consisting of constituents of Eurostoxx 600 and S&P 500.
Our experiments demonstrate that the LSTM-GCN model can capture additional
information from value chain data that are not fully reflected in price data,
and the predictions outperform baseline models on both datasets.
\\ ( https://arxiv.org/abs/2303.09406 ,  12840kb)
%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%
%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---
