Date: Fri, 17 Mar 23 00:51:30 GMT
Subject: q-fin.EC daily Subj-class mailing

------------------------------------------------------------------------------
------------------------------------------------------------------------------
Send any comments regarding submissions directly to submitter.
------------------------------------------------------------------------------
Archives at http://arxiv.org/
To unsubscribe, e-mail To: q-fin@arXiv.org, Subject: cancel
------------------------------------------------------------------------------
 Submissions to:
Economics
 received from  Wed 15 Mar 23 18:00:00 GMT  to  Thu 16 Mar 23 18:00:00 GMT
------------------------------------------------------------------------------
------------------------------------------------------------------------------
\\
arXiv:2303.09011
Date: Thu, 16 Mar 2023 00:55:52 GMT   (1252kb)

Title: Economics of In-Space Industry and Competitiveness of Lunar-Derived
  Rocket Propellant
Authors: Philip Metzger
Categories: econ.GN physics.soc-ph q-fin.EC
Comments: To be published in Acta Astronautica. 50 pages, 16 figures
\\
  Economic parameters are identified for an in-space industry where the capital
is made on one planet, it is transported to and teleoperated on a second
planet, and the product is transported off the second planet for consumption.
This framework is used to model the long-run cost of lunar propellant
production to help answer whether it is commercially competitive against
propellant launched from Earth. The prior techno-economic analyses (TEAs) of
lunar propellant production had disagreed over this. The "gear ratio on cost"
for capital transport, G, and the production mass ratio of the capital, phi,
are identified as the most important factors determining competitiveness. The
prior TEAs are examined for how they handled these two metrics. This identifies
crucial mistakes in some of the TEAs: choosing transportation architectures
with high G, and neglecting to make choices for the capital that could achieve
adequate phi. The tent sublimation technology has a value of phi that is an
order of magnitude better than the threshold for competitiveness even in low
Earth orbit (LEO). The strip mining technology is closer to the threshold, but
technological improvements plus several years of operating experience will
improve its competitiveness, according to the model. Objections from members of
the aerospace community are discussed, especially the question whether the
technology can attain adequate reliability in the lunar environment. The
results suggest that lunar propellant production will be commercially viable
and that it should lower the cost of doing everything else in space.
\\ ( https://arxiv.org/abs/2303.09011 ,  1252kb)
------------------------------------------------------------------------------
\\
arXiv:2303.09147
Date: Thu, 16 Mar 2023 08:22:17 GMT   (968kb)

Title: Economic Consequences of Online Tracking Restrictions
Authors: Klaus M. Miller and Bernd Skiera
Categories: econ.GN q-fin.EC
\\
  In recent years, European regulators have debated restricting the time an
online tracker can track a user to protect consumer privacy better. Despite the
significance of these debates, there has been a noticeable absence of any
comprehensive cost-benefit analysis. This article fills this gap on the cost
side by suggesting an approach to estimate the economic consequences of
lifetime restrictions on cookies for publishers. The empirical study on cookies
of 54,127 users who received 128 million ad impressions over 2.5 years yields
an average cookie lifetime of 279 days, with an average value of EUR 2.52 per
cookie. Only 13% of all cookies increase their daily value over time, but their
average value is about four times larger than the average value of all cookies.
Restricting cookies lifetime to one year (two years) decreases their lifetime
value by 25% (19%), which represents a decrease in the value of all cookies of
9% (5%). In light of the EUR 10.60 billion cookie-based display ad revenue in
Europe, such restrictions would endanger EUR 904 million (EUR 576 million)
annually, equivalent to EUR 2.08 (EUR 1.33) per EU internet user. The article
discusses these results' marketing strategy challenges and opportunities for
advertisers and publishers.
\\ ( https://arxiv.org/abs/2303.09147 ,  968kb)
------------------------------------------------------------------------------
\\
arXiv:2303.09399
Date: Mon, 13 Mar 2023 10:25:50 GMT   (5897kb)

Title: Main Concepts and Principles of Political Economy -- Production and
  Values, Distribution and Prices, Reproduction and Profits
Authors: Christian Flamant
Categories: econ.GN q-fin.EC
\\
  This book starts from the basic questions that had been raised by the
founders of Economic theory, Smith, Ricardo, and Marx: what makes the value of
commodities, what are production, exchange, money and incomes like profits,
wages and rents. The answers that these economists had provided were mostly
wrong, above all by defining the equivalence of commodities at the level of
exchange, but also because of a confusion made between values and prices, and
wrong views of what production really is and the role of fixed capital. Using
the mathematical theory of measurement and the physical theory of dimensional
analysis, this book provides a coherent theory of value based on an equivalence
relation not at the level of exchange, but of production. Indeed exchange is
considered here as an equivalence relation between money and a monetary price,
and not between commodities, modern monetary theory having demonstrated that
money is not a commodity. The book rejects the conception of production as a
surplus, which owes much to Sraffa's theory of production prices, and is shown
to be severely flawed. It founds the equivalence of commodities at the level of
a production process considered as a transformation process. It rehabilitates
the labor theory of value, based on the connection between money and labor due
the monetary payment of wages, which allows the homogenization of various kinds
of concrete labor into abstract labor. It shows that value is then a dimension
of commodities and that this dimension is time, i.e. the time of physics. On
this background, the book shows that the calculation of values for all
commodities is always possible, even in the case of joint production, and that
there cannot be any commodity residue left by this calculation. As a further
step, this book provides a coherent theory of the realization of the product,
which occurs in the circulation process. Using an idea - the widow's cruse -
introduced by Keynes in his Treatise on Money, it brings to light the mechanism
behind the transformation of money values into money prices and of
surplus-value into profits and other transfer incomes, ensuring the formation
of monetary profits. The book sheds some light on the rate of profit, its
determinants and its evolution, showing in particular the paramount importance
of capitalist consumption as one of its main determinants. In passing it
explains the reasons why in the real world there is a multiplicity of profit
rates. Finally, it allows to solve in a precise and illustrated way the
problems raised by the Marxist law of the tendency of the rate of profit to
fall. Most of the results obtained translate into principles, the first ones
being truly basic, the following ones less basic, but all of them being
fundamental. All in all, this book might provide the first building blocks to
develop a full-fledged and scientific economic theory to many fellow
economists, critical of neo-classical theory, but who have not yet dicovered
the bases of a complete and coherent alternative.
\\ ( https://arxiv.org/abs/2303.09399 ,  5897kb)
------------------------------------------------------------------------------
\\
arXiv:2303.09405
Date: Fri, 17 Feb 2023 09:23:51 GMT   (1014kb)

Title: Simplifying and Improving: Revisiting Bulgaria's Revenue Forecasting
  Models
Authors: Fabio Ashtar Telarico
Categories: econ.GN q-fin.EC stat.AP
Journal-ref: Economic Thought, 2023, 20 (6)
DOI: 10.56497/etj2367601
\\
  In the thirty years since the end of real socialism, Bulgaria's went from
having a rather radically 'different' tax system to adopting flat-rate taxation
with marginal tax rates that fell from figures as high as 40% to 10% for both
the corporate-income tax and the personal-income tax. Crucially, the
econometric forecasting models in use at the Bulgarian Ministry of Finance
hinted at an increase in tax revenue compatible with the so-called 'Laffer
curve'. Similarly, many economists held the view that revenues would have
increased. However, reality fell short of those expectations based on
forecasting models and rooted in mainstream economic theory. Thus, this paper
asks whether there are betterperforming forecasting models for personal-and
corporate-income tax-revenues in Bulgaria that are readily implementable and
overperform the ones currently in use. After articulating a constructive
critique of the current forecasting models, the paper offers readily
implementable, transparent alternatives and proves their superiority.
\\ ( https://arxiv.org/abs/2303.09405 ,  1014kb)
%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-
%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%
%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---
