Date: Fri, 17 Mar 23 00:51:30 GMT
Subject: q-fin.ST daily Subj-class mailing

------------------------------------------------------------------------------
------------------------------------------------------------------------------
Send any comments regarding submissions directly to submitter.
------------------------------------------------------------------------------
Archives at http://arxiv.org/
To unsubscribe, e-mail To: q-fin@arXiv.org, Subject: cancel
------------------------------------------------------------------------------
 Submissions to:
Statistical Finance
 received from  Wed 15 Mar 23 18:00:00 GMT  to  Thu 16 Mar 23 18:00:00 GMT
------------------------------------------------------------------------------
------------------------------------------------------------------------------
\\
arXiv:2303.09323
Date: Thu, 9 Mar 2023 01:29:09 GMT   (961kb,D)

Title: Stock Trend Prediction: A Semantic Segmentation Approach
Authors: Shima Nabiee, Nader Bagherzadeh
Categories: q-fin.ST cs.CV cs.LG
\\
  Market financial forecasting is a trending area in deep learning. Deep
learning models are capable of tackling the classic challenges in stock market
data, such as its extremely complicated dynamics as well as long-term temporal
correlation. To capture the temporal relationship among these time series,
recurrent neural networks are employed. However, it is difficult for recurrent
models to learn to keep track of long-term information. Convolutional Neural
Networks have been utilized to better capture the dynamics and extract features
for both short- and long-term forecasting. However, semantic segmentation and
its well-designed fully convolutional networks have never been studied for
time-series dense classification. We present a novel approach to predict
long-term daily stock price change trends with fully 2D-convolutional
encoder-decoders. We generate input frames with daily prices for a time-frame
of T days. The aim is to predict future trends by pixel-wise classification of
the current price frame. We propose a hierarchical CNN structure to encode
multiple price frames to multiscale latent representation in parallel using
Atrous Spatial Pyramid Pooling blocks and take that temporal coarse feature
stacks into account in the decoding stages. Our hierarchical structure of CNNs
makes it capable of capturing both long and short-term temporal relationships
effectively. The effect of increasing the input time horizon via incrementing
parallel encoders has been studied with interesting and substantial changes in
the output segmentation masks. We achieve overall accuracy and AUC of %78.18
and 0.88 for joint trend prediction over the next 20 days, surpassing other
semantic segmentation approaches. We compared our proposed model with several
deep models specifically designed for technical analysis and found that for
different output horizons, our proposed models outperformed other models.
\\ ( https://arxiv.org/abs/2303.09323 ,  961kb)
------------------------------------------------------------------------------
\\
arXiv:2303.09330
Date: Thu, 16 Mar 2023 14:02:30 GMT   (4092kb)

Title: Portfolio Volatility Estimation Relative to Stock Market Cross-Sectional
  Intrinsic Entropy
Authors: Claudiu Vinte, Marcel Ausloos
Categories: q-fin.ST
Comments: 24 pages, 12 figures, 4 tables
Journal-ref: Journal of Risk Financial Management 2023, 16(2), 114
DOI: 10.3390/jrfm16020114
\\
  Selecting stock portfolios and assessing their relative volatility risk
compared to the market as a whole, market indices, or other portfolios is of
great importance to professional fund managers and individual investors alike.
Our research uses the cross-sectional intrinsic entropy (CSIE) model to
estimate the cross-sectional volatility of the stock groups that can be
considered together as portfolio constituents. In our study, we benchmark
portfolio volatility risks against the volatility of the entire market provided
by the CSIE and the volatility of market indices computed using longitudinal
data. This article introduces CSIE-based betas to characterise the relative
volatility risk of the portfolio against market indices and the market as a
whole. We empirically prove that, through CSIE-based betas, multiple sets of
symbols that outperform the market indices in terms of rate of return while
maintaining the same level of risk or even lower than the one exhibited by the
market index can be discovered, for any given time interval. These sets of
symbols can be used as constituent stock portfolios and, in connection with the
perspective provided by the CSIE volatility estimates, to hierarchically assess
their relative volatility risk within the broader context of the overall
volatility of the stock market.
\\ ( https://arxiv.org/abs/2303.09330 ,  4092kb)
------------------------------------------------------------------------------
\\
arXiv:2303.09393
Date: Thu, 2 Feb 2023 10:26:12 GMT   (12918kb,D)

Title: A Deep Dive into NFT Whales: A Longitudinal Study of the NFT Trading
  Ecosystem
Authors: Na Hyeon Park, Hanna Kim, Chanhee Lee, Changhoon Yoon, Seunghyeon Lee,
  Youngjin jin, Seungwon Shin
Categories: q-fin.ST
\\
  NFT (Non-fungible Token) has drastically increased in its size, accounting
for over \$16.9B of total market capitalization. Despite the rapid growth of
NFTs, this market has not been examined thoroughly from a financial
perspective. In this paper, we conduct methodical analyses to identify NFT
market movers who play a significant role in potentially manipulating and
oscillating NFT values. We collect over 3.8M NFT transaction data from the
Ethereum Blockchain from January 2021 to February 2022 to extract trading
information in line with the NFT lifecycle: (i) mint, (ii) transfer/sale, and
(iii) burn. Based on the size of held NFT values, we classify NFT traders into
three groups (whales, dolphins, and minnows). In total, we analyze 430K traders
from 91 different NFT collection sources. We find that the top 0.1\% of NFT
traders (i.e., whales) drive the NFT market with consistent, high returns. We
then identify and characterize the NFT whales' unique investment strategies
(e.g., mint/sale patterns, wash trading) to empirically understand the whales
in the NFT market for the first time.
\\ ( https://arxiv.org/abs/2303.09393 ,  12918kb)
------------------------------------------------------------------------------
\\
arXiv:2303.09397
Date: Fri, 3 Mar 2023 18:42:01 GMT   (434kb)

Title: Cryptocurrency Price Prediction using Twitter Sentiment Analysis
Authors: Haritha GB and Sahana N.B
Categories: q-fin.ST cs.AI cs.CL cs.LG
Comments: 10 pages, NIAI 2023
DOI: 10.5121/csit.2023.130302
\\
  The cryptocurrency ecosystem has been the centre of discussion on many social
media platforms, following its noted volatility and varied opinions. Twitter is
rapidly being utilised as a news source and a medium for bitcoin discussion.
Our algorithm seeks to use historical prices and sentiment of tweets to
forecast the price of Bitcoin. In this study, we develop an end-to-end model
that can forecast the sentiment of a set of tweets (using a Bidirectional
Encoder Representations from Transformers - based Neural Network Model) and
forecast the price of Bitcoin (using Gated Recurrent Unit) using the predicted
sentiment and other metrics like historical cryptocurrency price data, tweet
volume, a user's following, and whether or not a user is verified. The
sentiment prediction gave a Mean Absolute Percentage Error of 9.45%, an average
of real-time data, and test data. The mean absolute percent error for the price
prediction was 3.6%.
\\ ( https://arxiv.org/abs/2303.09397 ,  434kb)
------------------------------------------------------------------------------
\\
arXiv:2303.09406
Date: Tue, 7 Mar 2023 17:24:04 GMT   (12840kb,D)

Title: Stock Price Prediction Using Temporal Graph Model with Value Chain Data
Authors: Chang Liu and Sandra Paterlini
Categories: q-fin.ST cs.LG q-fin.CP
\\
  Stock price prediction is a crucial element in financial trading as it allows
traders to make informed decisions about buying, selling, and holding stocks.
Accurate predictions of future stock prices can help traders optimize their
trading strategies and maximize their profits. In this paper, we introduce a
neural network-based stock return prediction method, the Long Short-Term Memory
Graph Convolutional Neural Network (LSTM-GCN) model, which combines the Graph
Convolutional Network (GCN) and Long Short-Term Memory (LSTM) Cells.
Specifically, the GCN is used to capture complex topological structures and
spatial dependence from value chain data, while the LSTM captures temporal
dependence and dynamic changes in stock returns data. We evaluated the LSTM-GCN
model on two datasets consisting of constituents of Eurostoxx 600 and S&P 500.
Our experiments demonstrate that the LSTM-GCN model can capture additional
information from value chain data that are not fully reflected in price data,
and the predictions outperform baseline models on both datasets.
\\ ( https://arxiv.org/abs/2303.09406 ,  12840kb)
------------------------------------------------------------------------------
\\
arXiv:2303.09407
Date: Tue, 14 Mar 2023 01:05:17 GMT   (1642kb)

Title: Improving CNN-base Stock Trading By Considering Data Heterogeneity and
  Burst
Authors: Keer Yang, Guanqun Zhang, Chuan Bi, Qiang Guan, Hailu Xu, Shuai Xu
Categories: q-fin.ST cs.LG
DOI: 10.5121/ijci.2023.120201
\\
  In recent years, there have been quite a few attempts to apply intelligent
techniques to financial trading, i.e., constructing automatic and intelligent
trading framework based on historical stock price. Due to the unpredictable,
uncertainty and volatile nature of financial market, researchers have also
resorted to deep learning to construct the intelligent trading framework. In
this paper, we propose to use CNN as the core functionality of such framework,
because it is able to learn the spatial dependency (i.e., between rows and
columns) of the input data. However, different with existing deep
learning-based trading frameworks, we develop novel normalization process to
prepare the stock data. In particular, we first empirically observe that the
stock data is intrinsically heterogeneous and bursty, and then validate the
heterogeneity and burst nature of stock data from a statistical perspective.
Next, we design the data normalization method in a way such that the data
heterogeneity is preserved and bursty events are suppressed. We verify out
developed CNN-based trading framework plus our new normalization method on 29
stocks. Experiment results show that our approach can outperform other
comparing approaches.
\\ ( https://arxiv.org/abs/2303.09407 ,  1642kb)
%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-
------------------------------------------------------------------------------
\\
arXiv:2303.09176 (*cross-listing*)
Date: Thu, 16 Mar 2023 09:38:40 GMT   (1633kb)

Title: Real Options Technique as a Tool of Strategic Risk Management
Authors: Volodymyr Savchuk
Categories: q-fin.RM q-fin.ST
Comments: 22 pages, 11 figures, 12 tables
\\
  The real options approach is now considered an effective alternative to the
corporate DCF model for a feasibility study. The current paper offers a
practical methodology employing binomial trees and real options techniques for
evaluating investment projects. A general computation procedure is suggested
for the decision tree with two active stages of real options, which correspond
to additional investments. The suggested technique can be used for most real
options, which are practically essential regarding enterprise strategy. The
special case named Binomial-Random-Cash-Flow Real Options Model with random
outcomes is developed as the next step of real options modelling. Project Value
at Risk is introduced and used as a criterion of investment project feasibility
under the assumption regarding random outcomes. In particular, the Gaussian
probability distribution is used for modelling option outcomes uncertainty. The
choice of the Gaussian distribution is caused by the desire to obtain estimates
in the final analytical form. Choosing another distribution for random outcomes
leads to using Monte Carlo simulation, for which a general framework is
developed by demonstrating some instances. The author could avoid the
computational complexity that makes these solutions feasible for business
practice.
\\ ( https://arxiv.org/abs/2303.09176 ,  1633kb)
%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%
------------------------------------------------------------------------------
\\
arXiv:2011.00552
replaced with revised version Wed, 15 Mar 2023 18:05:58 GMT   (829kb,D)

Title: Mixed--frequency quantile regressions to forecast Value--at--Risk and
  Expected Shortfall
Authors: Vincenzo Candila, Giampiero M. Gallo, Lea Petrella
Categories: q-fin.ST q-fin.RM
\\ ( https://arxiv.org/abs/2011.00552 ,  829kb)
%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---
