Date: Thu, 16 Mar 23 00:46:22 GMT
Subject: q-fin.PM daily Subj-class mailing

------------------------------------------------------------------------------
------------------------------------------------------------------------------
Send any comments regarding submissions directly to submitter.
------------------------------------------------------------------------------
Archives at http://arxiv.org/
To unsubscribe, e-mail To: q-fin@arXiv.org, Subject: cancel
------------------------------------------------------------------------------
 Submissions to:
Portfolio Management
 received from  Tue 14 Mar 23 18:00:00 GMT  to  Wed 15 Mar 23 18:00:00 GMT
------------------------------------------------------------------------------
------------------------------------------------------------------------------
\\
arXiv:2303.08462
Date: Wed, 15 Mar 2023 09:06:03 GMT   (1444kb,D)

Title: Optimal Investment in Defined Contribution Pension Schemes with Forward
  Utility Preferences
Authors: Kenneth Tsz Hin Ng, Wing Fung Chong
Categories: q-fin.PM
\\
  Optimal investment strategies of an individual worker during the accumulation
phase in the defined contribution pension scheme have been well studied in the
literature. Most of them adopted the classical backward model and approach, but
any pre-specifications of retirement time, preferences, and market environment
models do not often hold in such a prolonged horizon of the pension scheme.
Pre-commitment to ensure the time-consistency of an optimal investment strategy
derived from the backward model and approach leads the supposedly optimal
strategy to be sub-optimal in the actual realizations. This paper revisits the
optimal investment problem for the worker during the accumulation phase in the
defined contribution pension scheme, via the forward preferences which resolve
the pre-specification issues in the backward model and approach. Stochastic
partial differential equation representation for the worker's forward
preferences is illustrated. This paper constructs two of the forward utility
preferences and solves the corresponding optimal investment strategies, in the
cases of initial power and exponential utility functions.
\\ ( https://arxiv.org/abs/2303.08462 ,  1444kb)
------------------------------------------------------------------------------
\\
arXiv:2303.08521
Date: Wed, 15 Mar 2023 11:03:20 GMT   (283kb,D)

Title: Optimal investment in ambiguous financial markets with learning
Authors: Nicole B\"auerle and Antje Mahayni
Categories: q-fin.PM
\\
  We consider the classical multi-asset Merton investment problem under drift
uncertainty, i.e. the asset price dynamics are given by geometric Brownian
motions with constant but unknown drift coefficients. The investor assumes a
prior drift distribution and is able to learn by observing the asset prize
realizations during the investment horizon. While the solution of an expected
utility maximizing investor with constant relative risk aversion (CRRA) is well
known, we consider the optimization problem under risk and ambiguity
preferences by means of the KMM (Klibanoff et al. (2005)) approach. Here, the
investor maximizes a double certainty equivalent. The inner certainty
equivalent is for given drift coefficient, the outer is based on a drift
distribution. Assuming also a CRRA type ambiguity function, it turns out that
the optimal strategy can be stated in terms of the solution without ambiguity
preferences but an adjusted drift distribution. To the best of our knowledge an
explicit solution method in this setting is new. We rely on some duality
theorems to prove our statements.
  Based on our theoretical results, we are able to shed light on the impact of
the prior drift distribution as well as the consequences of ambiguity
preferences via the transfer to an adjusted drift distribution, i.e. we are
able to explain the interaction of risk and ambiguity preferences. We compare
our results with the ones in a pre-commitment setup where the investor is
restricted to deterministic strategies. It turns out that (under risk and
ambiguity aversion) an infinite investment horizon implies in both cases a
maximin decision rule, i.e. the investor follows the worst (best) Merton
fraction (over all realizations of it) if she is more (less) risk averse than a
log-investor. We illustrate our findings with an extensive numerical study.
\\ ( https://arxiv.org/abs/2303.08521 ,  283kb)
%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-
%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%--%%
------------------------------------------------------------------------------
\\
arXiv:1910.06463
replaced with revised version Tue, 14 Mar 2023 15:48:35 GMT   (495kb)

Title: Singular Perturbation Expansion for Utility Maximization with
  Order-$\epsilon$ Quadratic Transaction Costs
Authors: Andrew Papanicolaou and Shiva Chandra
Categories: q-fin.TR q-fin.PM
\\ ( https://arxiv.org/abs/1910.06463 ,  495kb)
%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---%%%---
