import mmh3


def create_hash(secret: str, url: str) -> str:
    """Creates a hash of the secret and url"""
    # murmer is faster and more random that MD5 which was used in arXiv classic
    return mmh3.hash_bytes(secret + url).hex()


def is_hash_valid(secret: str, url: str, ct_hash: str) -> bool:
    """Given the secret and url, check if ct_hash was generated by create_hash"""
    return ct_hash == create_hash(secret, url)


def create_ct_url(secret: str, url_for, url: str) -> str:
    """Creates a URL to the clickthrough service with a valid hash"""

    return url_for('browse.clickthrough', host=url, v=create_hash(secret, url))

