steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/dissemination:$SHORT_SHA', '.' ]

  - name: 'gcr.io/$PROJECT_ID/dissemination:$SHORT_SHA'
    entrypoint: '/bin/bash'
    args:
      - "-c"
      - |
        $GUNICORN &
        sleep 10
        pytest --runintegration
        exit_code=$?
        kill %1
        exit "$exit_code"



