steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/arxiv-browse:latest || echo "need a :latest because we use it for cache-from" && exit 0']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/arxiv-browse:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arxiv-browse:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arxiv-browse:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/arxiv-browse'
    id: Push
  # Not yet working:
  # - name: 'gcr.io/$PROJECT_ID/arxiv-browse:$COMMIT_SHA'
  #   script: |
  #       #!/usr/bin/env bash
  #       TRACE=0 TESTING=1 $GUNICORN &
  #       sleep 10
  #       pytest
  #       exit_code=$?
  #       kill %1
  #       exit "$exit_code"
  #   id: IntegrationTest
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=gcr.io/$PROJECT_ID/arxiv-browse:$COMMIT_SHA
      - >-
        --labels=commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images: ['gcr.io/$PROJECT_ID/arxiv-browse:latest', 'gcr.io/$PROJECT_ID/arxiv-browse:$COMMIT_SHA']



