steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 
              'build', 
              '-t', 
              'gcr.io/$PROJECT_ID/arxiv-browse:latest', 
              '--cache-from',
              'gcr.io/$PROJECT_ID/arxiv-browse:latest'
              '.'
          ]
images: ['gcr.io/$PROJECT_ID/arxiv-browse:latest']



