
steps:
  - name: 'python:3.10-slim'
    entrypoint: '/bin/bash'
    args:
      - "-c"
      - |
        pip install poetry
        poetry install
        export TRACE=0
        pytest --cov=arxiv_dissemination

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/dissemination:$SHORT_SHA', '.' ]
