
steps:
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip", "poetry"]     
  - name: python
    entrypoint: bash
    args: ["-c", "poetry", "install"]
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "--cov=arxiv_dissemination"]      
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/dissemination:$SHORT_SHA', '.' ]
