steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/dissemination:$SHORT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'run','gcr.io/$PROJECT_ID/dissemination:$SHORT_SHA', 'pytest' ]


