---
name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Test input"
        required: false
        type: string
        default: "test"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Test workflow ran successfully"
